# 1. Update config.yaml

artifacts_root: artifacts   # it will create one folder and everything will be saved in this folder.

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/imtiaz456/Branching_repositories/raw/main/NLP_Project.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion